CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS {{SCHEMA_NAME}};

CREATE TABLE IF NOT EXISTS {{TABLE_NAME}} (
    document_id TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    namespace TEXT,
    embedding {{VECTOR_TYPE}} NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS {{NAMESPACE_INDEX_NAME}}
    ON {{TABLE_NAME}} (namespace);

CREATE INDEX IF NOT EXISTS {{METADATA_INDEX_NAME}}
    ON {{TABLE_NAME}} USING GIN (metadata);

{{VECTOR_INDEX_SQL}}
